Fix compile errors due to default constructors
On some combination of compilers and STL implementations,
(I hit this using clang on Linux with libstdc++ from gcc 9)
hd/command.cpp fails to build with errors like:

usd/pxr/imaging/hd/command.cpp:30:22: error: defaulting this default constructor would delete it after its first declaration
HdCommandDescriptor::HdCommandDescriptor() = default;
                     ^
usd/pxr/imaging/hd/command.h:104:35: note: default constructor of 'HdCommandDescriptor' is implicitly deleted because field 'commandArgs' of const-qualified type 'const pxrInternal_v0_21__pxrReserved__::HdCommandArgDescriptors' (aka 'const vector<pxrInternal_v0_21__pxrReserved__::HdCommandArgDescriptor>') would not be initialized
    const HdCommandArgDescriptors commandArgs;

I believe this error is because commandArgs in HdCommandDescriptor
is a const std::vector member variable and C++ requires that it
have a user-provided constructor in order to generate the
default constructor for HdCommandDescriptor. The STL implementations
where this fails has an inline defaulted (i.e. not user-provided)
std::vector c'tor, which means the compiler is unable to generate
HdCommandDescriptor's default c'tor and errors out.

To fix this, we explicitly define empty constructors for
HdCommandDescriptor and HdCommandArgDescriptors. (Oh, C++).

Originally reported with a proposed fix in #1696.

Fixes #1696

(Internal change: 2231575)