[ndr] adds missing functional header
filesystemDiscoveryHelpers.h was missing an include to functional which caused a build failure.
The build error was the following:

error: "function" in namespace "std" does not name a template type