build_usd.py errors out on Windows with Python 3.8+
Python 3.8+ on Windows is currently not supported due to
this behavior change:

https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew

This behavior change causes runtime errors when loading
Python modules like:

ImportError: DLL load failed while importing _usd: The specified module could not be found.

The build script errors out now to help users avoid
creating an unusable build.

(Internal change: 2073284)